[package]
name = "terrain-rendering"
version = "0.1.0"
publish = false
edition = "2021"

[workspace]
members = ["plugins/*"]

[features]
default = [
    "bevy/dynamic"
]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "latest" }
app_plugin = { path = "plugins/app_plugin" }
