[package]
name = "terrain-rendering"
version = "0.1.0"
publish = false
edition = "2021"

[workspace]
members = ["plugins/*"]

[features]
default = [
    "bevy/dynamic"
]

[dependencies]
bevy = "0.6.0"
app_plugin = { path = "plugins/app_plugin" }

[patch.crates-io]
bevy = { git="https://github.com/fintelia/bevy" , branch = "renderpass-access"}