[package]
name = "map-generation"
version = "0.1.0"
publish = false
edition = "2018"

[features]
default = [
    "bevy/dynamic",
]

[dependencies]
bevy = "0.5.0"
game_plugin = { path = "game_plugin" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "map_generation"
harness = false
