[package]
name = "map-generation"
version = "0.1.0"
publish = false
edition = "2018"

[workspace]
members = ["plugins/*"]

[features]
default = [
    "bevy/dynamic"
]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
game_plugin = { path = "plugins/game_plugin" }
env_logger = "0.9.0"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "map_generation"
harness = false
