terrain_dir = "/Volumes/EXTERN_SSD/Terrains"
terrain = "Hartenstein_large"
preprocess = false

[[terrains]]
name = "Hartenstein"
side_length = 2
node_atlas_size = 1024
texture_size = 512
border_size = 1
mip_level_count = 1
node_count = 12
load_distance = 6.0
view_distance = 4.0
urls = [
    "tile_33334_5614",
    "tile_33334_5616",
    "tile_33336_5614",
    "tile_33336_5616",
]

[[terrains]]
name = "Hartenstein_large"
#node_atlas_size = 2000
#texture_size = 512
#border_size = 1
#mip_level_count = 1
#node_count = 22
#load_distance = 11.0
#view_distance = 10.0
side_length = 8

[[terrains]]
name = "Saxony"
side_length = 113
