[package]
name = "game_plugin"
version = "0.1.0"
publish = false
edition = "2018"

[features]
default = [
    "bevy/dynamic",
]

[dependencies]
bevy = "0.5.0"
bevy_config_cam = "0.1.2"
bevy-inspector-egui = "0.6.1"
nalgebra-glm = "0.14.0"
noise = "0.7.0"
rand = "0.8.4"